import argparse
import sys
from pathlib import Path
from typing import Optional

from libnxctrl.backend import get_available_backend, get_backend

from .plot import plot


BACKEND_NAMES = {
    "nxbt": "nxbt",
    "remote": "Remote",
    "usb": "Splatplost USB",
}


def serial_ports() -> list[str]:
    from serial.tools import list_ports

    return [port.device for port in list_ports.comports()]


def select_serial_port(requested_port: Optional[str]) -> str:
    if requested_port:
        return requested_port
    ports = serial_ports()
    if len(ports) == 1:
        print(f"Using the only detected serial port: {ports[0]}")
        return ports[0]
    if not ports:
        raise ValueError("No serial ports were detected. Connect the Splatplost USB adapter or pass --serial-port.")
    raise ValueError(
        "Multiple serial ports were detected; select one with --serial-port: " + ", ".join(ports)
    )


def resolve_backend(args: argparse.Namespace):
    available = get_available_backend()
    backend_key = args.backend
    if backend_key == "auto":
        preferred = ["usb", "nxbt"] if sys.platform == "win32" else ["nxbt", "usb"]
        backend_key = next(
            (key for key in preferred if BACKEND_NAMES[key] in available),
            "remote" if args.remote_server else "",
        )
        if not backend_key:
            raise ValueError("No local controller backend is available. Reinstall Splatplost with its platform extras.")

    backend_name = BACKEND_NAMES[backend_key]
    if backend_name not in available:
        raise ValueError(f"The {backend_key} backend is not available. Available backends: {', '.join(available)}")

    options = {}
    if backend_key == "usb":
        options["serial_port"] = select_serial_port(args.serial_port)
    elif backend_key == "remote":
        if not args.remote_server:
            raise ValueError("The remote backend requires --remote-server (for example http://192.168.1.10:15973).")
        options["conn_str"] = args.remote_server
    return get_backend(backend_name), options


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Draw a plot on a Nintendo Switch.")
    parser.add_argument(
        "--backend",
        choices=["auto", "usb", "remote", "nxbt"],
        default="auto",
        help="Controller backend (Windows auto defaults to USB).",
    )
    parser.add_argument("--serial-port", help="USB adapter serial port, for example COM3.")
    parser.add_argument("--remote-server", help="libnxctrl server URL for the remote backend.")
    parser.add_argument("--list-ports", action="store_true", help="List serial ports and exit.")
    parser.add_argument(
        "--delay-time-ms", "--delay_time_ms", type=int, default=100,
        help="Delay between controller steps.",
    )
    parser.add_argument(
        "--press-duration-ms", "--press_duration_ms", type=int, default=100,
        help="Duration of each controller step.",
    )
    parser.add_argument("--order", type=Path, help="Order file generated by splatplan.")
    parser.add_argument(
        "--stable", action="store_true",
        help="Queue the complete order before sending it (no progress bar).",
    )
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.list_ports:
        ports = serial_ports()
        print("\n".join(ports) if ports else "No serial ports detected.")
        return 0
    if args.order is None:
        parser.error("--order is required unless --list-ports is used")

    try:
        backend, backend_options = resolve_backend(args)
        with args.order.open(encoding="utf-8") as order_file:
            plot(
                order_list=order_file.readlines(),
                backend=backend,
                backend_options=backend_options,
                delay_ms=args.delay_time_ms,
                press_duration_ms=args.press_duration_ms,
                stable_mode=args.stable,
            )
    except (OSError, ValueError) as error:
        parser.exit(2, f"error: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
